### ISSUE TITLE
How convert keeping audio?

### ISSUE THREAD

**Issue by rezvalmo** [Mr-Z-2697/ddfi#1]
Hi 

I am new about this, just have that question, how can i convert a video keeping the audio?

Thanks for this amazing scrip.

**Comment by Mr-Z-2697** [comment]
Use -as 0 for convert with the default audio stream.

I'm sorry for the late reply.

**Comment by rezvalmo** [comment]
> 
> 
> Use -as 0 for convert with the default audio stream.
> 
> I'm sorry for the late reply.

ooh no problem, after several times i saw that, thanks.
